### ISSUE TITLE
Mobile keyboard pushed DOM elements up when keyboard is shown

### ISSUE THREAD

**Issue by jordanmcdougall** [jordanmcdougall/jordansviews#22]

**Comment by jordanmcdougall** [comment]
Try: 

```css
body {
  position: absolute;
}
```
